# Generated by Django 3.1.3 on 2020-11-09 09:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='file.file')),
            ],
            options={
                'db_table': 'post',
                'ordering': ['-timestamp'],
            },
        ),
    ]
